apiVersion: v1
kind: Pod
metadata:
  name: podaff
  labels:
    pod: aff
spec:
  containers:
    - name: contaff
      image: nginx
      ports:
        - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: website
                operator: In
                values:
                  - prod
